'use client'

import { createContext, useContext, useState, useEffect, ReactNode } from 'react'

type Language = 'id' | 'en'

interface LanguageContextType {
    language: Language
    setLanguage: (lang: Language) => void
    t: (key: string, params?: Record<string, string | number>) => string
}

const translations: Record<Language, Record<string, string>> = {
    id: {
        // Common
        'common.save': 'Simpan',
        'common.saveChanges': 'Simpan Perubahan',
        'common.cancel': 'Batal',
        'common.delete': 'Hapus',
        'common.edit': 'Edit',
        'common.add': 'Tambah',
        'common.search': 'Cari',
        'common.filter': 'Filter',
        'common.loading': 'Memuat...',
        'common.noData': 'Tidak ada data',
        'common.actions': 'Aksi',
        'common.status': 'Status',
        'common.back': 'Kembali',
        'common.welcome': 'Halo',
        'common.details': 'Detail',
        'common.view': 'Lihat',
        'common.print': 'Cetak',
        'common.confirm': 'Konfirmasi',
        'common.success': 'Berhasil',
        'common.error': 'Kesalahan',
        'common.close': 'Tutup',
        'common.tryAgain': 'Coba Lagi',
        'common.showing': 'Menampilkan',
        'common.of': 'dari',
        'common.data': 'data',
        'common.allStatus': 'Semua Status',
        'common.allCondition': 'Semua Kondisi',
        'common.yes': 'Ya',
        'common.no': 'Tidak',
        'common.process': 'Proses',
        'common.submit': 'Ajukan',
        'common.myAccount': 'Akun Saya',
        'common.mainPage': 'Halaman Utama',
        'common.selected': 'data dipilih',
        'common.confirmDelete': 'Konfirmasi Hapus',

        // Navigation
        'nav.dashboard': 'Dashboard',
        'nav.home': 'Beranda',
        'nav.users': 'Manajemen User',
        'nav.tools': 'Manajemen Alat',
        'nav.catalog': 'Katalog Alat',
        'nav.categories': 'Kategori Alat',
        'nav.loans': 'Data Peminjaman',
        'nav.myLoans': 'Peminjaman Saya',
        'nav.returns': 'Pengembalian Alat',
        'nav.validation': 'Validasi Peminjaman',
        'nav.reports': 'Laporan',
        'nav.activity': 'Log Aktivitas',
        'nav.settings': 'Pengaturan',
        'nav.logout': 'Keluar',

        // Settings
        'settings.title': 'Pengaturan',
        'settings.description': 'Kelola pengaturan aplikasi Anda.',
        'settings.theme': 'Tema Tampilan',
        'settings.themeDescription': 'Pilih tema tampilan yang Anda inginkan.',
        'settings.theme.light': 'Mode Terang',
        'settings.theme.dark': 'Mode Gelap',
        'settings.theme.system': 'Ikuti Sistem',
        'settings.language': 'Bahasa',
        'settings.languageDescription': 'Pilih bahasa yang ingin digunakan.',
        'settings.indonesian': 'Bahasa Indonesia',
        'settings.english': 'English',
        'settings.saved': 'Pengaturan berhasil disimpan!',
        'settings.themeChanged': 'Tema berhasil diubah!',
        'settings.userInfo': 'Informasi Pengguna',
        'settings.userInfoDescription': 'Perbarui informasi profil akun Anda.',
        'settings.security': 'Keamanan Password',
        'settings.securityDescription': 'Ubah password akun Anda untuk menjaga keamanan.',
        'settings.currentPassword': 'Password Saat Ini',
        'settings.newPassword': 'Password Baru',
        'settings.confirmPassword': 'Konfirmasi Password Baru',
        'settings.changePassword': 'Ubah Password',
        'settings.profileUpdated': 'Profil berhasil diperbarui!',
        'settings.passwordChanged': 'Password berhasil diubah!',
        'settings.passwordMismatch': 'Password baru tidak cocok dengan konfirmasi!',
        'settings.passwordTooShort': 'Password minimal 6 karakter!',
        'settings.profilePicture': 'Foto Profil',
        'settings.profilePictureDesc': 'Unggah foto profil baru.',

        // Home / Beranda
        'home.hero.subtitle': 'Platform Peminjaman Alat Digital',
        'home.hero.title': 'Halo, {name}!',
        'home.hero.description': 'Temukan dan pinjam berbagai alat laboratorium dengan mudah. Mulai perjalanan penelitian kamu di sini.',
        'home.hero.search': 'Cari Alat Sekarang',
        'home.hero.history': 'Riwayat Pinjam',
        'home.stats.activeLoans': 'Pinjaman Aktif',
        'home.stats.categories': 'Kategori',
        'home.alert.title': 'Pinjaman Perlu Diperhatikan',
        'home.alert.description': 'Ada {count} item yang sedang menunggu pengembalian.',
        'home.alert.button': 'Lihat Riwayat',
        'home.categories.badge': 'Eksplorasi',
        'home.categories.title': 'Eksplorasi Kategori',
        'home.tools.badge': 'Baru Ditambahkan',
        'home.tools.title': 'Alat Terbaru',
        'home.tools.viewAll': 'Lihat Semua',
        'home.tools.available': 'Tersedia',
        'home.tools.borrowed': 'Dipinjam',
        'home.tools.detail': 'Detail Alat',
        'home.tools.defaultDesc': 'Sempurnakan praktikum Anda dengan alat berkualitas tinggi ini.',
        'home.tools.noDesc': 'Tidak ada deskripsi tersedia untuk alat ini. Silakan hubungi petugas laboratorium untuk informasi lebih lanjut.',
        'home.categories.items': 'Item',

        // Dashboard
        'dashboard.title': 'Dashboard',
        'dashboard.subtitle': 'Ringkasan data sistem peminjaman alat',
        'dashboard.stats.totalUsers': 'Total User',
        'dashboard.stats.totalTools': 'Total Alat',
        'dashboard.stats.totalCategories': 'Total Kategori Alat',
        'dashboard.stats.activeLoans': 'Aktif Pinjam',
        'dashboard.stats.overdueLoans': 'Terlambat Kembali',
        'dashboard.stats.new': 'Baru',
        'dashboard.stats.needAction': 'Perlu Aksi',
        'dashboard.stats.pendingValidation': 'Perlu Validasi',
        'dashboard.stats.totalReturns': 'Total Pengembalian',
        'dashboard.stats.currentlyBorrowed': 'Sedang Dipinjam',
        'dashboard.stats.totalFines': 'Total Denda',
        'dashboard.stats.waiting': 'Menunggu',
        'dashboard.filter.time': 'Filter Waktu',
        'dashboard.filter.all': 'Semua Waktu',
        'dashboard.filter.today': 'Hari Ini',
        'dashboard.filter.thisMonth': 'Bulan Ini',
        'dashboard.filter.lastMonth': 'Bulan Lalu',
        'dashboard.filter.thisYear': 'Tahun Ini',
        'dashboard.autoRefresh.on': 'Auto On',
        'dashboard.autoRefresh.off': 'Auto Off',
        'dashboard.chart.monthly': 'Statistik Peminjaman',
        'dashboard.chart.monthlyDesc': 'Grafik tren peminjaman berdasarkan waktu',
        'dashboard.chart.popular': 'Kategori Populer',
        'dashboard.chart.popularDesc': 'Paling banyak dipinjam',
        'dashboard.activity.title': 'Aktivitas Terbaru',
        'dashboard.activity.subtitle': 'Riwayat aktivitas sistem terbaru',
        'dashboard.activity.viewAll': 'Lihat Semua',
        'dashboard.table.user': 'User',
        'dashboard.table.activity': 'Aktivitas',
        'dashboard.table.description': 'Deskripsi',
        'dashboard.table.time': 'Waktu',
        'dashboard.table.empty': 'Belum ada aktivitas tercatat',
        'dashboard.table.emptyDesc': 'Aktivitas sistem akan muncul di sini',
        'dashboard.detail.title': 'Detail Aktivitas',
        'dashboard.detail.related': 'Entitas Terkait',
        'dashboard.detail.techInfo': 'Informasi Teknis',
        'dashboard.recentLoans': 'Peminjaman Terbaru',
        'dashboard.recentLoansDesc': 'Daftar peminjaman alat terbaru',
        'dashboard.noLoanData': 'Belum ada data peminjaman',
        'dashboard.loansWillAppear': 'Peminjaman terbaru akan muncul di sini',

        // Role Titles
        'role.admin': 'Admin Panel',
        'role.petugas': 'Petugas Panel',
        'role.peminjam': 'Peminjam Panel',

        // Returns Page
        'returns.title': 'Data Pengembalian',
        'returns.subtitle': 'Kelola proses pengembalian alat dan monitoring denda.',
        'returns.processReturn': 'Proses Pengembalian',
        'returns.processReturnTitle': 'Proses Pengembalian Alat',
        'returns.processReturnDesc': 'Pilih peminjaman aktif untuk memproses pengembalian.',
        'returns.selectActiveLoan': 'Pilih Peminjaman Aktif',
        'returns.selectTransaction': '-- Pilih Transaksi Peminjaman --',
        'returns.returnDate': 'Tgl Kembali (Hari Ini)',
        'returns.toolCondition': 'Kondisi Alat',
        'returns.notes': 'Keterangan / Catatan',
        'returns.notesPlaceholder': 'Catatan mengenai kondisi alat atau keterlambatan...',
        'returns.saveReturn': 'Simpan Pengembalian',
        'returns.lateInfo': 'Terlambat {days} Hari',
        'returns.lateDescription': 'Peminjaman ini telah melewati batas waktu pengembalian. Dikenakan denda sebesar',
        'returns.onTimeInfo': 'Pengembalian tepat waktu. Tidak ada denda.',
        'returns.loanNo': 'No. Peminjaman',
        'returns.borrower': 'Peminjam',
        'returns.tool': 'Alat',
        'returns.loanDate': 'Tanggal Pinjam',
        'returns.plannedReturn': 'Rencana Kembali',
        'returns.actualReturn': 'Tanggal Kembali',
        'returns.fine': 'Denda',
        'returns.lateDays': 'Terlambat',
        'returns.days': 'Hari',
        'returns.noData': 'Tidak ada data pengembalian',
        'returns.noDataDesc': 'Silakan proses pengembalian baru',
        'returns.detailTitle': 'Detail Pengembalian',
        'returns.detailDesc': 'Informasi lengkap pengembalian alat.',
        'returns.editTitle': 'Edit Data Pengembalian',
        'returns.editDesc': 'Ubah kondisi alat atau keterangan jika ada kesalahan input.',
        'returns.deleteTitle': 'Hapus Data Pengembalian',
        'returns.deleteConfirm': 'Apakah Anda yakin ingin menghapus data pengembalian untuk',
        'returns.deleteWarning': 'Status peminjaman mungkin akan dikembalikan ke "Dipinjam".',
        'returns.saveChanges': 'Simpan Perubahan',
        'returns.yesDelete': 'Ya, Hapus',
        'returns.condition.good': 'Baik',
        'returns.condition.damaged': 'Rusak',
        'returns.condition.lost': 'Hilang',
        'returns.status.completed': 'Selesai',
        'returns.status.problem': 'Bermasalah',
        'returns.status.onTime': 'Tepat Waktu',
        'returns.status.late': 'Terlambat',
        'returns.returnTool': 'Kembalikan Alat',
        'returns.returnFormTitle': 'Form Pengembalian Alat',
        'returns.returnFormDesc': 'Pilih alat yang ingin Anda kembalikan dari daftar peminjaman aktif.',
        'returns.selectBorrowedTool': '-- Pilih Alat yang Dipinjam --',
        'returns.noActiveLoans': 'Tidak ada pinjaman aktif',
        'returns.allReturned': 'Semua alat telah dikembalikan.',
        'returns.processReturnBtn': 'Proses Pengembalian',
        'returns.returnSuccess': 'Pengembalian berhasil diproses!',
        'returns.returnFailed': 'Gagal memproses pengembalian',
        'returns.noHistory': 'Belum ada riwayat pengembalian',
        'returns.noHistoryDesc': 'Anda belum melakukan pengembalian alat apapun.',
        'returns.loanDuration': 'Durasi Pinjam',
        'returns.originalPlan': 'Awalnya',
        'returns.estimatedFine': 'Estimasi denda',
        'returns.peminjamSubtitle': 'Kelola pengembalian alat yang Anda pinjam.',
        'returns.selectActiveLoanLabel': 'Pilih Peminjaman Aktif',
        'returns.loanPrefix': 'Pinjam',
        'returns.planPrefix': 'Rencana',
        'returns.lateDaysInfo': 'Terlambat {days} hari. Estimasi denda: Rp {fine}',
        'returns.onTimeReturn': 'Pengembalian tepat waktu. Tidak ada denda.',
        'returns.notesPlaceholderLong': 'Contoh: Alat berfungsi normal, atau detail kerusakan...',
        'returns.showingResults': 'Menampilkan',
        'returns.dataResults': 'data',
        'returns.loanCode': 'Kode Peminjaman',
        'returns.closeButton': 'Tutup',
        'returns.filter.searchPlaceholder': 'Cari kode peminjaman, nama...',
        'returns.filter.allConditions': 'Semua Kondisi',
        'returns.filter.good': 'Baik',
        'returns.filter.minorDamage': 'Rusak Ringan',
        'returns.filter.majorDamage': 'Rusak Berat',
        'returns.filter.lost': 'Hilang',
        'returns.form.selectLoanLabel': 'Pilih Peminjaman Aktif',
        'returns.form.conditionLabel': 'Kondisi Alat',
        'returns.form.notesLabel': 'Keterangan / Catatan',
        'returns.form.notesPlaceholder': 'Catatan mengenai kondisi alat atau keterlambatan...',
        'returns.detail.title': 'Detail Pengembalian',
        'returns.detail.description': 'Informasi lengkap pengembalian alat.',
        'returns.detail.loanNo': 'No. Peminjaman',
        'returns.detail.endCondition': 'Kondisi Akhir',
        'returns.detail.realReturn': 'Realisasi Kembali',
        'returns.edit.title': 'Edit Data Pengembalian',
        'returns.edit.description': 'Ubah kondisi alat atau keterangan jika ada kesalahan input.',
        'returns.delete.title': 'Hapus Data Pengembalian',
        'returns.delete.confirm': 'Apakah Anda yakin ingin menghapus data pengembalian untuk {code}? Status peminjaman mungkin akan dikembalikan ke "Dipinjam".',
        'returns.delete.confirmAction': 'Ya, Hapus',
        'returns.status.lateMessage': 'Terlambat {days} Hari',
        'returns.status.lateFine': 'Peminjaman ini telah melewati batas waktu pengembalian. Dikenakan denda sebesar {amount}.',
        'returns.status.onTimeMessage': 'Pengembalian tepat waktu. Tidak ada denda.',
        'returns.table.loanNo': 'No. Peminjaman',
        'returns.table.borrower': 'Peminjam',
        'returns.table.tool': 'Alat',
        'returns.table.returnDate': 'Tgl Kembali',
        'returns.table.fine': 'Denda',
        'returns.table.status': 'Status',
        'returns.table.action': 'Aksi',
        'returns.table.plan': 'Rencana',
        'returns.table.date': 'Tgl',
        'returns.printReceipt': 'Cetak Bukti Pengembalian',
        'returns.printReceiptTitle': 'Bukti Pengembalian Alat',
        'returns.printReceiptSubtitle': 'Dokumen ini adalah bukti pengembalian alat yang sah',
        'returns.borrowerSignature': 'Tanda Tangan Peminjam',
        'returns.officerSignature': 'Tanda Tangan Petugas',
        'returns.printedAt': 'Dicetak pada',
        'returns.addFine': 'Tambah Denda',
        'returns.addFineTitle': 'Tambah Denda Tambahan',
        'returns.addFineDesc': 'Berikan denda tambahan untuk kerusakan atau kehilangan alat.',
        'returns.currentFine': 'Denda Saat Ini',
        'returns.additionalFineAmount': 'Jumlah Denda Tambahan (Rp)',
        'returns.newTotalFine': 'Total Denda Baru',
        'returns.bulkDeleteConfirm': 'Apakah Anda yakin ingin menghapus {count} data pengembalian yang dipilih? Tindakan ini tidak dapat dibatalkan.',
        'returns.selection.cancel': 'Batalkan Pilihan',
        'returns.selection.from': 'dari',
        'returns.selection.total': 'data dipilih (semua halaman)',
        'returns.selection.selected': 'data dipilih',
        'returns.selection.onPage': 'di halaman ini',
        'returns.selection.loading': 'Memuat...',
        'returns.selection.selectAll': 'Pilih semua {total} data pengembalian',

        // Validation Page
        'validation.title': 'Validasi Peminjaman',
        'validation.subtitle': 'Daftar permintaan peminjaman yang menunggu persetujuan Anda.',
        'validation.searchPlaceholder': 'Cari peminjam, alat, atau kode...',
        'validation.allClear': 'Semua Bersih!',
        'validation.noPending': 'Tidak ada permintaan peminjaman yang menunggu validasi saat ini. Kerja bagus!',
        'validation.loanDate': 'Tanggal Pinjam',
        'validation.returnPlan': 'Rencana Kembali',
        'validation.purpose': 'Keperluan Peminjaman',
        'validation.reject': 'Tolak',
        'validation.approve': 'Setujui',
        'validation.rejectTitle': 'Tolak Peminjaman',
        'validation.rejectDesc': 'Tindakan ini akan menolak permohonan peminjaman',
        'validation.rejectFrom': 'dari',
        'validation.rejectReason': 'Alasan Penolakan',
        'validation.rejectReasonOptional': '(Opsional)',
        'validation.rejectReasonPlaceholder': 'Jelaskan mengapa peminjaman ini ditolak (boleh dikosongkan)...',
        'validation.confirmReject': 'Konfirmasi Penolakan',
        'validation.approveSuccess': 'Peminjaman berhasil disetujui',
        'validation.rejectSuccess': 'Peminjaman ditolak',
        'validation.approveFailed': 'Gagal menyetujui peminjaman',
        'validation.rejectFailed': 'Gagal menolak peminjaman',
        'validation.loadFailed': 'Gagal memuat data peminjaman',
        'validation.lend': 'Pinjamkan',
        'validation.lendSuccess': 'Alat berhasil dipinjamkan',
        'validation.lendFailed': 'Gagal meminjamkan alat',
        'validation.lendConfirm': 'Konfirmasi pinjamkan alat untuk {code}? Status akan berubah menjadi "Dipinjam".',
        'validation.statusApproved': 'Disetujui',
        'validation.statusWaiting': 'Menunggu',

        // Reports Page
        'reports.title': 'Laporan & Cetak Data',
        'reports.subtitle': 'Generate laporan operasional sistem dalam format Excel maupun PDF.',
        'reports.loanReport': 'Laporan Peminjaman',
        'reports.loanReportDesc': 'Data histori seluruh peminjaman alat siswa.',
        'reports.returnReport': 'Laporan Pengembalian',
        'reports.returnReportDesc': 'Data alat yang telah dikembalikan beserta kondisinya.',
        'reports.fineReport': 'Laporan Denda & Sanksi',
        'reports.fineReportDesc': 'Rekapitulasi keterlambatan, kerusakan, dan denda.',
        'reports.fromDate': 'Dari Tanggal',
        'reports.toDate': 'Sampai Tanggal',
        'reports.categoryFilter': 'Filter Kategori (Opsional)',
        'reports.allCategories': 'Semua Kategori',
        'reports.exportGuide': 'Petunjuk Export Laporan',
        'reports.needHelp': 'Butuh Bantuan?',
        'reports.guideDescription': 'Butuh panduan lengkap? Klik tombol bantuan disamping untuk melihat langkah-langkah detail export laporan.',
        'reports.guideTitle': 'Panduan Export Laporan',
        'reports.guideSubtitle': 'Ikuti langkah-langkah di bawah ini untuk mengunduh laporan sistem.',
        'reports.step1Title': 'Pilih Jenis Laporan',
        'reports.step1Desc': 'Tentukan jenis laporan yang ingin dicetak (Peminjaman, Pengembalian, atau Denda) pada kartu yang tersedia.',
        'reports.step2Title': 'Tentukan Rentang Waktu',
        'reports.step2Desc': 'Isi field "Dari Tanggal" dan "Sampai Tanggal". Data yang diambil adalah data yang masuk dalam rentang tersebut.',
        'reports.step3Title': 'Filter Kategori (Opsional)',
        'reports.step3Desc': 'Anda dapat memfilter laporan berdasarkan kategori alat tertentu jika diperlukan. Biarkan default untuk semua kategori.',
        'reports.step4Title': 'Unduh File',
        'reports.step4Desc': 'Klik tombol Excel untuk format spreadsheet yang dapat diedit, atau PDF untuk dokumen siap cetak.',
        'reports.understand': 'Mengerti',
        'reports.exportSuccess': 'Laporan {type} berhasil diexport ke {format}',
        'reports.exportFailed': 'Gagal export laporan',
        'reports.dateRequired': 'Silakan masukkan rentang tanggal terlebih dahulu',
        'reports.dateInvalid': 'Tanggal awal tidak boleh lebih besar dari tanggal akhir',

        // Loans Page
        'loans.title': 'Data Peminjaman',
        'loans.subtitle': 'Kelola data peminjaman alat pribadi Anda.',
        'loans.applyLoan': 'Ajukan Peminjaman',
        'loans.applyNewLoan': 'Ajukan Peminjaman Baru',
        'loans.applyLoanDesc': 'Isi formulir di bawah ini untuk mengajukan peminjaman alat.',
        'loans.selectTool': 'Pilih Alat',
        'loans.chooseTool': '-- Pilih Alat --',
        'loans.loanDate': 'Tanggal Pinjam',
        'loans.returnDatePlan': 'Tanggal Kembali (Rencana)',
        'loans.quantity': 'Jumlah',
        'loans.purpose': 'Keperluan',
        'loans.purposePlaceholder': 'Contoh: Praktikum Fisika',
        'loans.searchPlaceholder': 'Cari kode, nama alat...',
        'loans.code': 'Kode',
        'loans.stock': 'Stok',
        'loans.noLoanData': 'Tidak ada data peminjaman',
        'loans.noLoanDataDesc': 'Ajukan peminjaman baru atau ubah filter pencarian',
        'loans.detailTitle': 'Detail Peminjaman',
        'loans.detailDesc': 'Informasi lengkap pengajuan peminjaman alat.',
        'loans.loanCode': 'KODE PEMINJAMAN',
        'loans.requestDate': 'Tgl Pengajuan',
        'loans.entity': 'Entitas',
        'loans.validationNotes': 'Catatan Validasi',
        'loans.status.pending': 'Menunggu',
        'loans.status.approved': 'Disetujui',
        'loans.status.borrowed': 'Dipinjam',
        'loans.status.rejected': 'Ditolak',
        'loans.status.returned': 'Selesai',
        'loans.status.overdue': 'Terlambat',
        'loans.printProof': 'Cetak Bukti Pengajuan',
        'loans.proofTitle': 'Bukti Pengajuan Peminjaman Alat',
        'loans.proofSubtitle': 'Dokumen ini adalah bukti pengajuan peminjaman yang telah disetujui',
        'loans.proofBorrower': 'Nama Peminjam',
        'loans.proofTool': 'Nama Alat',
        'loans.proofToolCode': 'Kode Alat',
        'loans.proofQty': 'Jumlah',
        'loans.proofPurpose': 'Keperluan',
        'loans.proofNote': 'Catatan: Tunjukkan bukti ini kepada petugas saat mengambil alat.',
        'loans.printLoanProof': 'Cetak Bukti Peminjaman',
        'loans.loanProofTitle': 'Bukti Peminjaman Alat',
        'loans.loanProofSubtitle': 'Dokumen ini adalah bukti peminjaman alat yang sah',
        'loans.loanProofNote': 'Harap kembalikan alat sesuai tanggal yang ditentukan.',
        'loans.borrowerSignature': 'Tanda Tangan Peminjam',
        'loans.officerSignature': 'Tanda Tangan Petugas',
        'loans.printedAt': 'Dicetak pada',

        // Admin Loans Page
        'adminLoans.title': 'Data Peminjaman',
        'adminLoans.subtitle': 'Kelola semua data peminjaman alat dalam sistem.',
        'adminLoans.add': 'Tambah Peminjaman',
        'adminLoans.addTitle': 'Tambah Peminjaman Baru',
        'adminLoans.addDesc': 'Buat pengajuan peminjaman alat baru. Klik simpan untuk menambahkan.',
        'adminLoans.approve': 'Setujui',
        'adminLoans.approveTitle': 'Setujui Peminjaman',
        'adminLoans.approveDesc': 'Apakah Anda yakin ingin menyetujui peminjaman {code}? Stok alat akan dikurangi sesuai jumlah yang dipinjam.',
        'adminLoans.confirmApprove': 'Ya, Setujui',
        'adminLoans.reject': 'Tolak',
        'adminLoans.rejectTitle': 'Tolak Peminjaman',
        'adminLoans.rejectDesc': 'Apakah Anda yakin ingin menolak peminjaman {code}?',
        'adminLoans.rejectReason': 'Alasan Penolakan',
        'adminLoans.delete': 'Hapus',
        'adminLoans.deleteTitle': 'Hapus Peminjaman',
        'adminLoans.deleteDesc': 'Apakah Anda yakin ingin menghapus peminjaman {code}? Tindakan ini tidak dapat dibatalkan.',
        'adminLoans.form.borrower': 'Peminjam (Opsional)',
        'adminLoans.form.selectBorrower': '-- Pilih Peminjam --',
        'adminLoans.form.tool': 'Alat *',
        'adminLoans.form.selectTool': '-- Pilih Alat --',
        'adminLoans.form.amount': 'Jumlah',
        'adminLoans.form.loanDate': 'Tanggal Pinjam *',
        'adminLoans.form.returnDate': 'Tanggal Rencana Kembali *',
        'adminLoans.form.purpose': 'Keperluan *',
        'adminLoans.form.purposePlaceholder': 'Jelaskan keperluan peminjaman...',
        'adminLoans.searchPlaceholder': 'Cari kode, nama peminjam, alat...',
        'adminLoans.detailTitle': 'Detail Peminjaman',
        'adminLoans.status.waiting': 'Menunggu',
        'adminLoans.status.approved': 'Disetujui',
        'adminLoans.status.borrowed': 'Dipinjam',
        'adminLoans.status.rejected': 'Ditolak',
        'adminLoans.status.returned': 'Selesai',
        'adminLoans.status.late': 'Terlambat',
        'adminLoans.table.code': 'Kode',
        'adminLoans.table.borrower': 'Peminjam',
        'adminLoans.table.tool': 'Alat',
        'adminLoans.table.loanDate': 'Tgl Pinjam',
        'adminLoans.table.returnDate': 'Tgl Rencana Kembali',
        'adminLoans.table.status': 'Status',
        'adminLoans.table.action': 'Aksi',
        'adminLoans.detail.borrowedDate': 'Diajukan',
        'adminLoans.detail.quantity': 'Jumlah',
        'adminLoans.detail.validatedBy': 'Divalidasi Oleh',
        'adminLoans.detail.validationNote': 'Catatan Validasi',
        'adminLoans.lend': 'Pinjamkan',
        'adminLoans.lendTitle': 'Pinjamkan Alat',
        'adminLoans.lendDesc': 'Apakah Anda yakin ingin meminjamkan alat untuk peminjaman {code}? Status akan berubah menjadi "Dipinjam".',
        'adminLoans.confirmLend': 'Ya, Pinjamkan',
        'adminLoans.selection.cancel': 'Batalkan Pilihan',
        'adminLoans.selection.from': 'dari',
        'adminLoans.selection.total': 'data dipilih (semua halaman)',
        'adminLoans.selection.selected': 'data dipilih',
        'adminLoans.selection.onPage': 'di halaman ini',
        'adminLoans.selection.loading': 'Memuat...',
        'adminLoans.selection.selectAll': 'Pilih semua {total} data peminjaman',

        // Catalog
        'catalog.title': 'Katalog Alat',
        'catalog.subtitle': 'Temukan berbagai alat laboratorium yang tersedia untuk dipinjam.',
        'catalog.searchPlaceholder': 'Cari nama alat...',
        'catalog.allCategories': 'Semua Kategori',
        'catalog.availability': 'Ketersediaan',
        'catalog.condition': 'Kondisi Alat',
        'catalog.unit': 'Unit',
        'catalog.outOfStock': 'Habis',
        'catalog.available': 'Tersedia',
        'catalog.errorField': 'Mohon lengkapi semua field form peminjaman.',
        'catalog.errorStock': 'Jumlah peminjaman melebihi stok tersedia.',
        'catalog.heroTitle': 'Katalog Alat',
        'catalog.heroDesc': 'Temukan alat yang Anda butuhkan untuk kegiatan praktik sekolah.',
        'catalog.noTools': 'Tidak ada alat ditemukan',
        'catalog.noToolsDesc': 'Coba kata kunci lain atau ubah filter kategori pencarian Anda.',
        'catalog.noDescription': 'Tidak ada deskripsi tersedia untuk alat ini.',
        'catalog.borrow': 'Pinjam',
        'catalog.availableStockCaps': 'STOK TERSEDIA',
        'catalog.toolConditionCaps': 'KONDISI ALAT',
        'catalog.startBorrowing': 'MULAI PEMINJAMAN',
        'catalog.borrowTitle': 'Ajukan Peminjaman',
        'catalog.borrowDesc': 'Silakan lengkapi detail rencana peminjaman Anda.',
        'catalog.borrowDateCaps': 'TANGGAL PINJAM',
        'catalog.returnPlanCaps': 'RENCANA KEMBALI',
        'catalog.quantityCaps': 'JUMLAH ALAT',
        'catalog.borrowPurposeCaps': 'KEPERLUAN PINJAM',
        'catalog.purposePlaceholder': 'Sebutkan alasan atau lokasi kegiatan praktik...',
        'catalog.submit': 'Kirim',
        'catalog.maintenance': 'Maintenance',

        // User Management
        'users.title': 'Manajemen User',
        'users.subtitle': 'Kelola data pengguna sistem.',
        'users.addUser': 'Tambah User',
        'users.name': 'Nama',
        'users.namePlaceholder': 'Masukkan nama lengkap',
        'users.email': 'Email',
        'users.emailPlaceholder': 'Masukkan alamat email',
        'users.phone': 'No. Telepon',
        'users.phonePlaceholder': 'Masukkan nomor telepon',
        'users.address': 'Alamat',
        'users.addressPlaceholder': 'Masukkan alamat lengkap',
        'users.role': 'Role',
        'users.password': 'Password',
        'users.addTitle': 'Tambah User Baru',
        'users.addDesc': 'Isi detail pengguna baru di bawah ini. Klik simpan untuk menambahkan user.',
        'users.editTitle': 'Edit User',
        'users.editDesc': 'Ubah detail pengguna yang terdaftar.',
        'users.deleteTitle': 'Hapus User',
        'users.deleteConfirm': 'Apakah Anda yakin ingin menghapus user {name}?',
        'users.deleteWarning': 'Tindakan ini tidak dapat dibatalkan.',
        'users.save': 'Simpan User',
        'users.saveChanges': 'Simpan Perubahan',
        'users.searchPlaceholder': 'Cari nama, email, atau ID...',
        'users.selectRole': 'Semua Role',
        'users.selectStatus': 'Semua Status',
        'users.noData': 'Tidak ada data user',
        'users.noDataDesc': 'Tambah user baru atau ubah filter pencarian',
        'users.joined': 'Bergabung {date}',
        'users.status.active': 'Aktif',
        'users.status.inactive': 'Nonaktif',
        'users.role.admin': 'Administrator',
        'users.role.petugas': 'Petugas',
        'users.role.peminjam': 'Peminjam',
        'users.roleDesc.admin': 'Akses penuh sistem',
        'users.roleDesc.petugas': 'Kelola peminjaman',
        'users.roleDesc.peminjam': 'Pengguna sistem',
        'users.passwordHint': 'Minimal 6 karakter',
        'users.passwordEditHint': 'Password Baru (Kosongkan jika tidak diubah)',
        'users.passwordValidation': 'Password harus minimal 6 karakter!',
        'users.optional': '(Opsional)',


        // Tool Management
        'tools.title': 'Manajemen Alat',
        'tools.subtitle': 'Kelola data alat laboratorium.',
        'tools.addTool': 'Tambah Alat',
        'tools.code': 'Kode',
        'tools.name': 'Nama',
        'tools.category': 'Kategori',
        'tools.totalStock': 'Stok Total',
        'tools.availableStock': 'Stok Tersedia',
        'tools.condition': 'Kondisi',
        'tools.image': 'Gambar',
        'tools.action': 'Aksi',
        'tools.addTitle': 'Tambah Alat Baru',
        'tools.addDesc': 'Masukkan informasi lengkap mengenai alat baru yang akan diinventarisir.',
        'tools.editTitle': 'Edit Alat',
        'tools.editDesc': 'Perbarui informasi alat inventaris.',
        'tools.deleteTitle': 'Hapus Alat',
        'tools.deleteConfirm': 'Apakah Anda yakin ingin menghapus alat {name}?',
        'tools.deleteWarning': 'Tindakan ini tidak dapat dibatalkan.',
        'tools.searchPlaceholder': 'Cari nama alat, kode, atau kategori...',
        'tools.selectCategory': 'Pilih Kategori',
        'tools.selectCondition': 'Pilih Kondisi',
        'tools.selectStatus': 'Pilih Status',
        'tools.initialStock': 'Stok Awal',
        'tools.descPlaceholder': 'Deskripsi singkat alat...',
        'tools.photo': 'Foto Alat',
        'tools.uploadPhoto': 'Klik untuk upload foto',
        'tools.photoFormat': 'JPEG, PNG, WebP (max 5MB)',
        'tools.uploading': 'Mengupload...',
        'tools.save': 'Simpan Alat',
        'tools.saveChanges': 'Simpan Perubahan',
        'tools.noData': 'Tidak ada data alat',
        'tools.noDataDesc': 'Tambah alat baru atau ubah filter pencarian',
        'tools.ofUnits': 'dari {total} unit',
        'tools.status.available': 'Tersedia',
        'tools.status.outOfStock': 'Habis',
        'tools.status.maintenance': 'Perbaikan',
        'tools.condition.good': 'Baik',
        'tools.condition.damaged': 'Rusak',
        'tools.condition.lost': 'Hilang',


        // Category Management
        'categories.title': 'Manajemen Kategori',
        'categories.subtitle': 'Kelola kategori alat laboratorium.',
        'categories.addCategory': 'Tambah Kategori',
        'categories.name': 'Nama Kategori',
        'categories.description': 'Deskripsi',
        'categories.toolCount': 'Jumlah Alat',
        'categories.addTitle': 'Tambah Kategori Baru',
        'categories.addDesc': 'Buat kategori baru untuk mengelompokkan alat-alat.',
        'categories.namePlaceholder': 'Contoh: Multimedia',
        'categories.descPlaceholder': 'Deskripsi singkat kategori...',
        'categories.save': 'Simpan Kategori',
        'categories.searchPlaceholder': 'Cari kategori...',
        'categories.noData': 'Tidak ada kategori',
        'categories.noDataDesc': 'Tambah kategori baru untuk mengelompokkan alat',
        'categories.items': 'item',
        'categories.viewTools': 'Lihat Alat',
        'categories.createNew': 'Buat Kategori Baru',
        'categories.editTitle': 'Edit Kategori',
        'categories.editDesc': 'Ubah detail kategori.',
        'categories.deleteTitle': 'Hapus Kategori',
        'categories.deleteConfirm': 'Apakah Anda yakin ingin menghapus kategori {name}?',
        'categories.deleteWarning': 'Kategori ini memiliki {count} alat. Hapus semua alat terlebih dahulu.',
        'categories.saveChanges': 'Simpan Perubahan',


        // Activity Log
        'activityLog.title': 'Log Aktivitas',
        'activityLog.subtitle': 'Pantau dan kelola riwayat aktivitas sistem.',
        'activityLog.header.user': 'User',
        'activityLog.header.action': 'Aksi',
        'activityLog.header.table': 'Tabel / Record',
        'activityLog.header.description': 'Deskripsi',
        'activityLog.header.time': 'Waktu',
        'activityLog.filter.searchPlaceholder': 'Cari deskripsi, user, atau tabel...',
        'activityLog.filter.allActions': 'Semua Aksi',
        'activityLog.filter.create': 'Create',
        'activityLog.filter.update': 'Update',
        'activityLog.filter.delete': 'Delete',
        'activityLog.filter.login': 'Login',
        'activityLog.filter.logout': 'Logout',
        'activityLog.selection.selected': 'log dipilih',
        'activityLog.selection.onPage': 'di halaman ini',
        'activityLog.selection.from': 'dari',
        'activityLog.selection.total': 'total log (semua halaman)',
        'activityLog.selection.selectAll': 'Pilih semua {total} log',
        'activityLog.selection.loading': 'Memuat...',
        'activityLog.selection.cancel': 'Batalkan Pilihan',
        'activityLog.delete.button': 'Hapus ({count}) Terpilih',
        'activityLog.delete.title': 'Hapus Log Aktivitas',
        'activityLog.delete.confirm': 'Apakah Anda yakin ingin menghapus {count} log aktivitas yang dipilih? Tindakan ini tidak dapat dibatalkan.',
        'activityLog.delete.confirmAction': 'Ya, Hapus',
        'activityLog.delete.cancel': 'Batal',
        'activityLog.detail.title': 'Detail Aktivitas',
        'activityLog.detail.noDescription': 'Tidak ada deskripsi detail.',
        'activityLog.detail.entity': 'Entitas Terkait',
        'activityLog.detail.technical': 'Informasi Teknis',
        'activityLog.detail.userStamp': 'User Stamp',
        'activityLog.detail.table': 'Tabel:',
        'activityLog.detail.recordId': 'Record ID:',
        'activityLog.detail.ipAddress': 'IP Address',
        'activityLog.detail.serverTime': 'Waktu Server',
        'activityLog.empty.title': 'Tidak ada log aktivitas',
        'activityLog.empty.description': 'Belum ada aktivitas yang tercatat sesuai filter ini.',

        // Dashboard Dynamic
        'dashboard.timeAgo.justNow': 'Baru saja',
        'dashboard.timeAgo.minutes': '{count} menit lalu',
        'dashboard.timeAgo.hours': '{count} jam lalu',
        'dashboard.timeAgo.days': '{count} hari lalu',
        'dashboard.action.create': 'menambah',
        'dashboard.action.update': 'mengubah',
        'dashboard.action.delete': 'menghapus',
        'dashboard.action.login': 'masuk sistem',
        'dashboard.action.logout': 'keluar sistem',
        'dashboard.action.approve': 'menyetujui',
        'dashboard.action.reject': 'menolak',
        'dashboard.action.return': 'memproses pengembalian',
        'dashboard.entity.peminjaman': 'peminjaman',
        'dashboard.entity.pengembalian': 'pengembalian',
        'dashboard.entity.alat': 'alat',
        'dashboard.entity.user': 'user',
        'dashboard.entity.users': 'user',
        'dashboard.entity.kategori': 'kategori',
        'dashboard.entity.log_aktivitas': 'log aktivitas',

        // Login Page
        'login.hero.title': 'Kelola Peralatan dengan Lebih Efisien',
        'login.hero.subtitle': 'Peminjaman Alat',
        'login.hero.description': 'Sistem yang terintegrasi untuk meminjam, mengembalikan, dan mengelola inventaris dengan real-time.',
        'login.welcome': 'Selamat Datang!',
        'login.subtitle': 'Silakan masuk ke dalam akun Anda untuk mengelola peralatan dengan lebih mudah.',
        'login.email': 'Email',
        'login.emailPlaceholder': 'Masukkan email atau username',
        'login.password': 'Password',
        'login.passwordPlaceholder': 'Masukkan password',
        'login.signIn': 'Masuk',
        'login.signingIn': 'Sedang Masuk...',
        // 'login.mobileBrand': 'Peminjaman Alat',
        'login.error.generic': 'Terjadi kesalahan saat login',



    },
    en: {
        // Common
        'common.save': 'Save',
        'common.saveChanges': 'Save Changes',
        'common.cancel': 'Cancel',
        'common.delete': 'Delete',
        'common.edit': 'Edit',
        'common.add': 'Add',
        'common.search': 'Search',
        'common.filter': 'Filter',
        'common.loading': 'Loading...',
        'common.noData': 'No data',
        'common.actions': 'Actions',
        'common.status': 'Status',
        'common.back': 'Back',
        'common.welcome': 'Welcome',
        'common.details': 'Details',
        'common.view': 'View',
        'common.print': 'Print',
        'common.confirm': 'Confirm',
        'common.success': 'Success',
        'common.error': 'Error',
        'common.close': 'Close',
        'common.tryAgain': 'Try Again',
        'common.showing': 'Showing',
        'common.of': 'of',
        'common.data': 'data',
        'common.allStatus': 'All Status',
        'common.allCondition': 'All Conditions',
        'common.yes': 'Yes',
        'common.no': 'No',
        'common.process': 'Process',
        'common.submit': 'Submit',
        'common.myAccount': 'My Account',
        'common.mainPage': 'Main Page',
        'common.selected': 'selected',
        'common.confirmDelete': 'Confirm Delete',

        // Navigation
        'nav.dashboard': 'Dashboard',
        'nav.home': 'Home',
        'nav.users': 'User Management',
        'nav.tools': 'Tool Management',
        'nav.catalog': 'Tool Catalog',
        'nav.categories': 'Tool Categories',
        'nav.loans': 'Loan Data',
        'nav.myLoans': 'My Loans',
        'nav.returns': 'Tool Returns',
        'nav.validation': 'Loan Validation',
        'nav.reports': 'Reports',
        'nav.activity': 'Activity Log',
        'nav.settings': 'Settings',
        'nav.logout': 'Logout',

        // Settings
        'settings.title': 'Settings',
        'settings.description': 'Manage your application settings.',
        'settings.theme': 'Display Theme',
        'settings.themeDescription': 'Choose your preferred display theme.',
        'settings.theme.light': 'Light Mode',
        'settings.theme.dark': 'Dark Mode',
        'settings.theme.system': 'System Default',
        'settings.language': 'Language',
        'settings.languageDescription': 'Choose your preferred language.',
        'settings.indonesian': 'Bahasa Indonesia',
        'settings.english': 'English',
        'settings.saved': 'Settings saved successfully!',
        'settings.themeChanged': 'Theme changed successfully!',
        'settings.userInfo': 'User Information',
        'settings.userInfoDescription': 'Update your profile information.',
        'settings.security': 'Password Security',
        'settings.securityDescription': 'Change your password to keep your account secure.',
        'settings.currentPassword': 'Current Password',
        'settings.newPassword': 'New Password',
        'settings.confirmPassword': 'Confirm New Password',
        'settings.changePassword': 'Change Password',
        'settings.profileUpdated': 'Profile updated successfully!',
        'settings.passwordChanged': 'Password changed successfully!',
        'settings.passwordMismatch': 'New password does not match confirmation!',
        'settings.passwordTooShort': 'Password must be at least 6 characters!',
        'settings.profilePicture': 'Profile Picture',
        'settings.profilePictureDesc': 'Upload a new profile picture.',

        // Home / Beranda
        'home.hero.subtitle': 'Digital Tool Loan Platform',
        'home.hero.title': 'Hello, {name}!',
        'home.hero.description': 'Discover and borrow various laboratory tools easily. Start your research journey here.',
        'home.hero.search': 'Search Tools Now',
        'home.hero.history': 'Loan History',
        'home.stats.activeLoans': 'Active Loans',
        'home.stats.categories': 'Categories',
        'home.alert.title': 'Loans Needing Attention',
        'home.alert.description': 'There are {count} items waiting to be returned.',
        'home.alert.button': 'View History',
        'home.categories.badge': 'Explore',
        'home.categories.title': 'Explore Categories',
        'home.tools.badge': 'Newly Added',
        'home.tools.title': 'Latest Tools',
        'home.tools.viewAll': 'View All',
        'home.tools.available': 'Available',
        'home.tools.borrowed': 'Borrowed',
        'home.tools.detail': 'Tool Detail',
        'home.tools.defaultDesc': 'Enhance your practicum with this high-quality tool.',
        'home.tools.noDesc': 'No description available for this tool. Please contact laboratory staff for more information.',
        'home.categories.items': 'Items',

        // Dashboard
        'dashboard.title': 'Dashboard',
        'dashboard.subtitle': 'Summary of tool loaning system data',
        'dashboard.stats.totalUsers': 'Total Users',
        'dashboard.stats.totalTools': 'Total Tools',
        'dashboard.stats.totalCategories': 'Total Tool Categories',
        'dashboard.stats.activeLoans': 'Active Loans',
        'dashboard.stats.overdueLoans': 'Overdue Returns',
        'dashboard.stats.new': 'New',
        'dashboard.stats.needAction': 'Need Action',
        'dashboard.stats.pendingValidation': 'Pending Validation',
        'dashboard.stats.totalReturns': 'Total Returns',
        'dashboard.stats.currentlyBorrowed': 'Currently Borrowed',
        'dashboard.stats.totalFines': 'Total Fines',
        'dashboard.stats.waiting': 'Waiting',
        'dashboard.filter.time': 'Time Filter',
        'dashboard.filter.all': 'All Time',
        'dashboard.filter.today': 'Today',
        'dashboard.filter.thisMonth': 'This Month',
        'dashboard.filter.lastMonth': 'Last Month',
        'dashboard.filter.thisYear': 'This Year',
        'dashboard.autoRefresh.on': 'Auto On',
        'dashboard.autoRefresh.off': 'Auto Off',
        'dashboard.chart.monthly': 'Loan Statistics',
        'dashboard.chart.monthlyDesc': 'Loan trend chart over time',
        'dashboard.chart.popular': 'Popular Categories',
        'dashboard.chart.popularDesc': 'Most borrowed items',
        'dashboard.activity.title': 'Recent Activity',
        'dashboard.activity.subtitle': 'Recent system activity logs',
        'dashboard.activity.viewAll': 'View All',
        'dashboard.table.user': 'User',
        'dashboard.table.activity': 'Activity',
        'dashboard.table.description': 'Description',
        'dashboard.table.time': 'Time',
        'dashboard.table.empty': 'No activity recorded yet',
        'dashboard.table.emptyDesc': 'System activities will appear here',
        'dashboard.detail.title': 'Activity Details',
        'dashboard.detail.related': 'Related Entities',
        'dashboard.detail.techInfo': 'Technical Info',
        'dashboard.recentLoans': 'Recent Loans',
        'dashboard.recentLoansDesc': 'List of recent tool loans',
        'returns.bulkDeleteConfirm': 'Are you sure you want to delete {count} selected return records? This action cannot be undone.',

        // Admin Loans Page
        'adminLoans.title': 'Loan Data',
        'adminLoans.subtitle': 'Manage all tool loan data in the system.',
        'adminLoans.add': 'Add Loan',
        'adminLoans.addTitle': 'Add New Loan',
        'adminLoans.addDesc': 'Create a new tool loan request. Click save to add.',
        'adminLoans.approve': 'Approve',
        'adminLoans.approveTitle': 'Approve Loan',
        'adminLoans.approveDesc': 'Are you sure you want to approve loan {code}? Tool stock will be reduced by the loan amount.',
        'adminLoans.confirmApprove': 'Yes, Approve',
        'adminLoans.reject': 'Reject',
        'adminLoans.rejectTitle': 'Reject Loan',
        'adminLoans.rejectDesc': 'Are you sure you want to reject loan {code}?',
        'adminLoans.rejectReason': 'Rejection Reason',
        'adminLoans.delete': 'Delete',
        'adminLoans.deleteTitle': 'Delete Loan',
        'adminLoans.deleteDesc': 'Are you sure you want to delete loan {code}? This action cannot be undone.',
        'adminLoans.form.borrower': 'Borrower (Optional)',
        'adminLoans.form.selectBorrower': '-- Select Borrower --',
        'adminLoans.form.tool': 'Tool *',
        'adminLoans.form.selectTool': '-- Select Tool --',
        'adminLoans.form.amount': 'Amount',
        'adminLoans.form.loanDate': 'Loan Date *',
        'adminLoans.form.returnDate': 'Planned Return Date *',
        'adminLoans.form.purpose': 'Purpose *',
        'adminLoans.form.purposePlaceholder': 'Explain loan purpose...',
        'adminLoans.searchPlaceholder': 'Search code, borrower name, tool...',
        'adminLoans.detailTitle': 'Loan Detail',
        'adminLoans.status.waiting': 'Waiting',
        'adminLoans.status.approved': 'Approved',
        'adminLoans.status.borrowed': 'Borrowed',
        'adminLoans.status.rejected': 'Rejected',
        'adminLoans.status.returned': 'Completed',
        'adminLoans.status.late': 'Overdue',
        'adminLoans.table.code': 'Code',
        'adminLoans.table.borrower': 'Borrower',
        'adminLoans.table.tool': 'Tool',
        'adminLoans.table.loanDate': 'Loan Date',
        'adminLoans.table.returnDate': 'Planned Return',
        'adminLoans.table.status': 'Status',
        'adminLoans.table.action': 'Action',
        'adminLoans.detail.borrowedDate': 'Requested',
        'adminLoans.detail.quantity': 'Quantity',
        'adminLoans.detail.validatedBy': 'Validated By',
        'adminLoans.detail.validationNote': 'Validation Note',
        'adminLoans.lend': 'Lend',
        'adminLoans.lendTitle': 'Lend Tool',
        'adminLoans.lendDesc': 'Are you sure you want to lend the tool for loan {code}? Status will change to "Borrowed".',
        'adminLoans.confirmLend': 'Yes, Lend',
        'dashboard.noLoanData': 'No loan data yet',
        'dashboard.loansWillAppear': 'Recent loans will appear here',
        'adminLoans.selection.cancel': 'Cancel Selection',
        'adminLoans.selection.from': 'from',
        'adminLoans.selection.total': 'data selected (all pages)',
        'adminLoans.selection.selected': 'data selected',
        'adminLoans.selection.onPage': 'on this page',
        'adminLoans.selection.loading': 'Loading...',

        // Role Titles
        'role.admin': 'Admin Panel',
        'role.petugas': 'Staff Panel',
        'role.peminjam': 'Borrower Panel',

        // Login Page
        'login.hero.title': 'Manage Tools More Efficiently',
        'login.hero.subtitle': 'Tool Lending',
        'login.hero.description': 'An integrated system to borrow, return, and manage inventory in real-time.',
        'login.welcome': 'Welcome Back!',
        'login.subtitle': 'Please sign in to your account to manage tools more easily.',
        'login.email': 'Email',
        'login.emailPlaceholder': 'Enter email or username',
        'login.password': 'Password',
        'login.passwordPlaceholder': 'Enter password',
        'login.signIn': 'Sign In',
        'login.signingIn': 'Signing in...',
        // 'login.mobileBrand': 'Tool Lending',
        'login.error.generic': 'An error occurred during login',

        // Returns Page
        'returns.title': 'Return Data',
        'returns.subtitle': 'Manage tool return process and fine monitoring.',
        'returns.processReturn': 'Process Return',
        'returns.processReturnTitle': 'Process Tool Return',
        'returns.processReturnDesc': 'Select an active loan to process the return.',
        'returns.selectActiveLoan': 'Select Active Loan',
        'returns.selectTransaction': '-- Select Loan Transaction --',
        'returns.returnDate': 'Return Date (Today)',
        'returns.toolCondition': 'Tool Condition',
        'returns.notes': 'Notes / Comments',
        'returns.notesPlaceholder': 'Notes about tool condition or lateness...',
        'returns.saveReturn': 'Save Return',
        'returns.lateInfo': 'Late {days} Days',
        'returns.lateDescription': 'This loan has exceeded the return deadline. Subject to a fine of',
        'returns.onTimeInfo': 'On-time return. No fine.',
        'returns.loanNo': 'Loan No.',
        'returns.borrower': 'Borrower',
        'returns.tool': 'Tool',
        'returns.loanDate': 'Loan Date',
        'returns.plannedReturn': 'Planned Return',
        'returns.actualReturn': 'Actual Return',
        'returns.fine': 'Fine',
        'returns.addFine': 'Add Fine',
        'returns.addFineTitle': 'Add Additional Fine',
        'returns.addFineDesc': 'Add additional fine for tool damage or loss.',
        'returns.currentFine': 'Current Fine',
        'returns.additionalFineAmount': 'Additional Fine Amount (Rp)',
        'returns.newTotalFine': 'New Total Fine',
        'returns.selection.cancel': 'Cancel Selection',
        'returns.selection.from': 'from',
        'returns.selection.total': 'data selected (all pages)',
        'returns.selection.selected': 'data selected',
        'returns.selection.onPage': 'on this page',
        'returns.selection.loading': 'Loading...',
        'returns.selection.selectAll': 'Select all {total} data returns',

        // Dashboard Dynamic
        'dashboard.timeAgo.justNow': 'Just now',
        'dashboard.timeAgo.minutes': '{count} minutes ago',
        'dashboard.timeAgo.hours': '{count} hours ago',
        'dashboard.timeAgo.days': '{count} days ago',
        'dashboard.action.create': 'created',
        'dashboard.action.update': 'updated',
        'dashboard.action.delete': 'deleted',
        'dashboard.action.login': 'logged in',
        'dashboard.action.logout': 'logged out',
        'dashboard.action.approve': 'approved',
        'dashboard.action.reject': 'rejected',
        'dashboard.action.return': 'processed return',
        'dashboard.entity.peminjaman': 'loan',
        'dashboard.entity.pengembalian': 'return',
        'dashboard.entity.alat': 'tool',
        'dashboard.entity.user': 'user',
        'dashboard.entity.users': 'user',
        'dashboard.entity.kategori': 'category',
        'dashboard.entity.log_aktivitas': 'activity log',

        'returns.lateDays': 'Late',
        'returns.days': 'Days',
        'returns.noData': 'No return data',
        'returns.filter.searchPlaceholder': 'Search loan code, name...',
        'returns.filter.allConditions': 'All Conditions',
        'returns.filter.good': 'Good',
        'returns.filter.minorDamage': 'Minor Damage',
        'returns.filter.majorDamage': 'Major Damage',
        'returns.filter.lost': 'Lost',
        'returns.form.selectLoanLabel': 'Select Active Loan',
        'returns.form.conditionLabel': 'Tool Condition',
        'returns.form.notesLabel': 'Notes / Comments',
        'returns.form.notesPlaceholder': 'Notes about tool condition or lateness...',
        'returns.detail.title': 'Return Detail',
        'returns.detail.description': 'Complete return information.',
        'returns.detail.loanNo': 'Loan No.',
        'returns.detail.endCondition': 'End Condition',
        'returns.detail.realReturn': 'Actual Return',
        'returns.edit.title': 'Edit Return Data',
        'returns.edit.description': 'Modify tool condition or notes if there is an input error.',
        'returns.delete.title': 'Delete Return Data',
        'returns.delete.confirm': 'Are you sure you want to delete return data for {code}? Loan status might revert to "Borrowed".',
        'returns.delete.confirmAction': 'Yes, Delete',
        'returns.status.lateMessage': 'Late {days} Day(s)',
        'returns.status.lateFine': 'This loan has exceeded the return deadline. Subject to a fine of {amount}.',
        'returns.status.onTimeMessage': 'On-time return. No fine.',
        'returns.table.loanNo': 'Loan No.',
        'returns.table.borrower': 'Borrower',
        'returns.table.tool': 'Tool',
        'returns.table.returnDate': 'Return Date',
        'returns.table.fine': 'Fine',
        'returns.table.status': 'Status',
        'returns.table.action': 'Action',
        'returns.table.plan': 'Plan',
        'returns.table.date': 'Date',
        'returns.printReceipt': 'Print Return Receipt',
        'returns.printReceiptTitle': 'Tool Return Receipt',
        'returns.printReceiptSubtitle': 'This document is a valid proof of tool return',
        'returns.borrowerSignature': 'Borrower Signature',
        'returns.officerSignature': 'Officer Signature',
        'returns.printedAt': 'Printed at',
        'returns.noDataDesc': 'Please process a new return',
        'returns.detailTitle': 'Return Details',
        'returns.detailDesc': 'Complete information about the tool return.',
        'returns.editTitle': 'Edit Return Data',
        'returns.editDesc': 'Change tool condition or notes if there was an input error.',
        'returns.deleteTitle': 'Delete Return Data',
        'returns.deleteConfirm': 'Are you sure you want to delete the return data for',
        'returns.deleteWarning': 'The loan status may be reverted to "Borrowed".',
        'returns.saveChanges': 'Save Changes',
        'returns.yesDelete': 'Yes, Delete',
        'returns.condition.good': 'Good',
        'returns.condition.damaged': 'Damaged',
        'returns.condition.lost': 'Lost',
        'returns.status.completed': 'Completed',
        'returns.status.problem': 'Problematic',
        'returns.status.onTime': 'On Time',
        'returns.status.late': 'Late',
        'returns.returnTool': 'Return Tool',
        'returns.returnFormTitle': 'Tool Return Form',
        'returns.returnFormDesc': 'Choose a tool you want to return from your active loan list.',
        'returns.selectBorrowedTool': '-- Choose Borrowed Tool --',
        'returns.noActiveLoans': 'No active loans',
        'returns.allReturned': 'All tools have been returned.',
        'returns.processReturnBtn': 'Process Return',
        'returns.returnSuccess': 'Return processed successfully!',
        'returns.returnFailed': 'Failed to process return',
        'returns.noHistory': 'No return history yet',
        'returns.noHistoryDesc': 'You haven\'t returned any tools yet.',
        'returns.loanDuration': 'Loan Duration',
        'returns.originalPlan': 'Originally',
        'returns.estimatedFine': 'Estimated fine',
        'returns.peminjamSubtitle': 'Manage returns for the tools you borrowed.',
        'returns.selectActiveLoanLabel': 'Select Active Loan',
        'returns.loanPrefix': 'Loan',
        'returns.planPrefix': 'Plan',
        'returns.lateDaysInfo': 'Late {days} days. Estimated fine: Rp {fine}',
        'returns.onTimeReturn': 'On-time return. No fine.',
        'returns.notesPlaceholderLong': 'Example: Tool works normally, or damage details...',
        'returns.showingResults': 'Showing',
        'returns.dataResults': 'results',
        'returns.loanCode': 'Loan Code',
        'returns.closeButton': 'Close',

        // Validation Page
        'validation.title': 'Loan Validation',
        'validation.subtitle': 'List of loan requests awaiting your approval.',
        'validation.searchPlaceholder': 'Search borrower, tool, or code...',
        'validation.allClear': 'All Clear!',
        'validation.noPending': 'No loan requests pending validation at this time. Good job!',
        'validation.loanDate': 'Loan Date',
        'validation.returnPlan': 'Return Plan',
        'validation.purpose': 'Loan Purpose',
        'validation.reject': 'Reject',
        'validation.approve': 'Approve',
        'validation.rejectTitle': 'Reject Loan',
        'validation.rejectDesc': 'This action will reject the loan request',
        'validation.rejectFrom': 'from',
        'validation.rejectReason': 'Rejection Reason',
        'validation.rejectReasonOptional': '(Optional)',
        'validation.rejectReasonPlaceholder': 'Explain why this loan is rejected (can be left empty)...',
        'validation.confirmReject': 'Confirm Rejection',
        'validation.approveSuccess': 'Loan approved successfully',
        'validation.rejectSuccess': 'Loan rejected',
        'validation.approveFailed': 'Failed to approve loan',
        'validation.rejectFailed': 'Failed to reject loan',
        'validation.loadFailed': 'Failed to load loan data',
        'validation.lend': 'Lend',
        'validation.lendSuccess': 'Tool successfully lent',
        'validation.lendFailed': 'Failed to lend tool',
        'validation.lendConfirm': 'Confirm lending tool for {code}? Status will change to "Borrowed".',
        'validation.statusApproved': 'Approved',
        'validation.statusWaiting': 'Waiting',

        // Reports Page
        'reports.title': 'Reports & Print Data',
        'reports.subtitle': 'Generate operational reports in Excel or PDF format.',
        'reports.loanReport': 'Loan Report',
        'reports.loanReportDesc': 'History data of all student tool loans.',
        'reports.returnReport': 'Return Report',
        'reports.returnReportDesc': 'Data of returned tools and their conditions.',
        'reports.fineReport': 'Fine & Penalty Report',
        'reports.fineReportDesc': 'Summary of late returns, damages, and fines.',
        'reports.fromDate': 'From Date',
        'reports.toDate': 'To Date',
        'reports.categoryFilter': 'Category Filter (Optional)',
        'reports.allCategories': 'All Categories',
        'reports.exportGuide': 'Export Guide',
        'reports.needHelp': 'Need Help?',
        'reports.guideDescription': 'Need a complete guide? Click the help button to see detailed export steps.',
        'reports.guideTitle': 'Report Export Guide',
        'reports.guideSubtitle': 'Follow the steps below to download system reports.',
        'reports.step1Title': 'Select Report Type',
        'reports.step1Desc': 'Choose the type of report to print (Loans, Returns, or Fines) from the available cards.',
        'reports.step2Title': 'Set Date Range',
        'reports.step2Desc': 'Fill in the "From Date" and "To Date" fields. Data within this range will be included.',
        'reports.step3Title': 'Category Filter (Optional)',
        'reports.step3Desc': 'You can filter reports by specific tool categories if needed. Leave default for all categories.',
        'reports.step4Title': 'Download File',
        'reports.step4Desc': 'Click the Excel button for an editable spreadsheet format, or PDF for a print-ready document.',
        'reports.understand': 'Got it',
        'reports.exportSuccess': '{type} report exported successfully to {format}',
        'reports.exportFailed': 'Failed to export report',
        'reports.dateRequired': 'Please enter a date range first',
        'reports.dateInvalid': 'Start date cannot be greater than end date',

        // Loans Page
        'loans.title': 'Loan Data',
        'loans.subtitle': 'Manage your personal tool loan data.',
        'loans.applyLoan': 'Apply for Loan',
        'loans.applyNewLoan': 'Apply for New Loan',
        'loans.applyLoanDesc': 'Fill out the form below to apply for a tool loan.',
        'loans.selectTool': 'Select Tool',
        'loans.chooseTool': '-- Choose Tool --',
        'loans.loanDate': 'Loan Date',
        'loans.returnDatePlan': 'Return Date (Plan)',
        'loans.quantity': 'Quantity',
        'loans.purpose': 'Purpose',
        'loans.purposePlaceholder': 'Example: Physics Practicum',
        'loans.searchPlaceholder': 'Search code, tool name...',
        'loans.code': 'Code',
        'loans.stock': 'Stock',
        'loans.noLoanData': 'No loan data',
        'loans.noLoanDataDesc': 'Apply for a new loan or change search filters',
        'loans.detailTitle': 'Loan Details',
        'loans.detailDesc': 'Complete information about the tool loan request.',
        'loans.loanCode': 'LOAN CODE',
        'loans.requestDate': 'Request Date',
        'loans.entity': 'Entity',
        'loans.validationNotes': 'Validation Notes',
        'loans.status.pending': 'Pending',
        'loans.status.approved': 'Approved',
        'loans.status.borrowed': 'Borrowed',
        'loans.status.rejected': 'Rejected',
        'loans.status.returned': 'Completed',
        'loans.status.overdue': 'Overdue',
        'loans.printProof': 'Print Submission Proof',
        'loans.proofTitle': 'Tool Loan Application Proof',
        'loans.proofSubtitle': 'This document is proof of an approved loan application',
        'loans.proofBorrower': 'Borrower Name',
        'loans.proofTool': 'Tool Name',
        'loans.proofToolCode': 'Tool Code',
        'loans.proofQty': 'Quantity',
        'loans.proofPurpose': 'Purpose',
        'loans.proofNote': 'Note: Show this proof to staff when picking up the tool.',
        'loans.printLoanProof': 'Print Loan Proof',
        'loans.loanProofTitle': 'Tool Loan Proof',
        'loans.loanProofSubtitle': 'This document is a valid proof of tool loan',
        'loans.loanProofNote': 'Please return the tool on the specified date.',
        'loans.borrowerSignature': 'Borrower Signature',
        'loans.officerSignature': 'Officer Signature',
        'loans.printedAt': 'Printed at',


        // Catalog
        'catalog.title': 'Tool Catalog',
        'catalog.subtitle': 'Find various laboratory tools available for borrowing.',
        'catalog.searchPlaceholder': 'Search tool name...',
        'catalog.allCategories': 'All Categories',
        'catalog.availability': 'Availability',
        'catalog.condition': 'Tool Condition',
        'catalog.unit': 'Unit',
        'catalog.outOfStock': 'Out of Stock',
        'catalog.available': 'Available',
        'catalog.errorField': 'Please complete all loan form fields.',
        'catalog.errorStock': 'Loan quantity exceeds available stock.',
        'catalog.heroTitle': 'Tool Catalog',
        'catalog.heroDesc': 'Find the tools you need for your school practical activities.',
        'catalog.noTools': 'No tools found',
        'catalog.noToolsDesc': 'Try another keyword or change your search category filter.',
        'catalog.noDescription': 'No description available for this tool.',
        'catalog.borrow': 'Borrow',
        'catalog.availableStockCaps': 'AVAILABLE STOCK',
        'catalog.toolConditionCaps': 'TOOL CONDITION',
        'catalog.startBorrowing': 'START BORROWING',
        'catalog.borrowTitle': 'Apply for Loan',
        'catalog.borrowDesc': 'Please complete your borrowing plan details.',
        'catalog.borrowDateCaps': 'BORROW DATE',
        'catalog.returnPlanCaps': 'RETURN PLAN',
        'catalog.quantityCaps': 'QUANTITY',
        'catalog.borrowPurposeCaps': 'BORROW PURPOSE',
        'catalog.purposePlaceholder': 'State the reason or location of your practical activity...',
        'catalog.submit': 'Submit',
        'catalog.maintenance': 'Maintenance',

        // User Management
        'users.title': 'User Management',
        'users.subtitle': 'Manage system user data.',
        'users.addUser': 'Add User',
        'users.name': 'Name',
        'users.namePlaceholder': 'Enter full name',
        'users.email': 'Email',
        'users.emailPlaceholder': 'Enter email address',
        'users.phone': 'Phone Number',
        'users.phonePlaceholder': 'Enter phone number',
        'users.address': 'Address',
        'users.addressPlaceholder': 'Enter full address',
        'users.role': 'Role',
        'users.password': 'Password',
        'users.addTitle': 'Add New User',
        'users.addDesc': 'Enter new user details below. Click save to add user.',
        'users.editTitle': 'Edit User',
        'users.editDesc': 'Edit registered user details.',
        'users.deleteTitle': 'Delete User',
        'users.deleteConfirm': 'Are you sure you want to delete user {name}?',
        'users.deleteWarning': 'This action cannot be undone.',
        'users.save': 'Save User',
        'users.saveChanges': 'Save Changes',
        'users.searchPlaceholder': 'Search name, email, or ID...',
        'users.selectRole': 'All Roles',
        'users.selectStatus': 'All Status',
        'users.noData': 'No user data',
        'users.noDataDesc': 'Add new user or change search filters',
        'users.joined': 'Joined {date}',
        'users.status.active': 'Active',
        'users.status.inactive': 'Inactive',
        'users.role.admin': 'Administrator',
        'users.role.petugas': 'Staff',
        'users.role.peminjam': 'Borrower',
        'users.roleDesc.admin': 'Full system access',
        'users.roleDesc.petugas': 'Manage loans',
        'users.roleDesc.peminjam': 'System user',
        'users.passwordHint': 'Minimum 6 characters',
        'users.passwordEditHint': 'New Password (Leave blank if unchanged)',
        'users.passwordValidation': 'Password must be at least 6 characters!',
        'users.optional': '(Optional)',


        // Tool Management
        'tools.title': 'Tool Management',
        'tools.subtitle': 'Manage laboratory tool data.',
        'tools.addTool': 'Add Tool',
        'tools.code': 'Code',
        'tools.name': 'Name',
        'tools.category': 'Category',
        'tools.totalStock': 'Total Stock',
        'tools.availableStock': 'Available Stock',
        'tools.condition': 'Condition',
        'tools.image': 'Image',
        'tools.action': 'Action',
        'tools.addTitle': 'Add New Tool',
        'tools.addDesc': 'Enter complete information about the new tool to be inventoried.',
        'tools.editTitle': 'Edit Tool',
        'tools.editDesc': 'Update inventory tool information.',
        'tools.deleteTitle': 'Delete Tool',
        'tools.deleteConfirm': 'Are you sure you want to delete tool {name}?',
        'tools.deleteWarning': 'This action cannot be undone.',
        'tools.searchPlaceholder': 'Search tool name, code, or category...',
        'tools.selectCategory': 'Select Category',
        'tools.selectCondition': 'Select Condition',
        'tools.selectStatus': 'Select Status',
        'tools.initialStock': 'Initial Stock',
        'tools.descPlaceholder': 'Short tool description...',
        'tools.photo': 'Tool Photo',
        'tools.uploadPhoto': 'Click to upload photo',
        'tools.photoFormat': 'JPEG, PNG, WebP (max 5MB)',
        'tools.uploading': 'Uploading...',
        'tools.save': 'Save Tool',
        'tools.saveChanges': 'Save Changes',
        'tools.noData': 'No tool data',
        'tools.noDataDesc': 'Add a new tool or change search filters',
        'tools.ofUnits': 'of {total} units',
        'tools.status.available': 'Available',
        'tools.status.outOfStock': 'Out of Stock',
        'tools.status.maintenance': 'Maintenance',
        'tools.condition.good': 'Good',
        'tools.condition.damaged': 'Damaged',
        'tools.condition.lost': 'Lost',


        // Category Management
        'categories.title': 'Category Management',
        'categories.subtitle': 'Manage laboratory tool categories.',
        'categories.addCategory': 'Add Category',
        'categories.name': 'Category Name',
        'categories.description': 'Description',
        'categories.toolCount': 'Tool Count',
        'categories.addTitle': 'Add New Category',
        'categories.addDesc': 'Create a new category to group tools.',
        'categories.namePlaceholder': 'Example: Multimedia',
        'categories.descPlaceholder': 'Short category description...',
        'categories.save': 'Save Category',
        'categories.searchPlaceholder': 'Search categories...',
        'categories.noData': 'No categories',
        'categories.noDataDesc': 'Add a new category to group tools',
        'categories.items': 'items',
        'categories.viewTools': 'View Tools',
        'categories.createNew': 'Create New Category',
        'categories.editTitle': 'Edit Category',
        'categories.editDesc': 'Update category details.',
        'categories.deleteTitle': 'Delete Category',
        'categories.deleteConfirm': 'Are you sure you want to delete category {name}?',
        'categories.deleteWarning': 'This category has {count} tools. Please delete all tools first.',
        'categories.saveChanges': 'Save Changes',


        // Activity Log
        'activityLog.title': 'Activity Log',
        'activityLog.subtitle': 'Monitor and manage system activity history.',
        'activityLog.header.user': 'User',
        'activityLog.header.action': 'Action',
        'activityLog.header.table': 'Table / Record',
        'activityLog.header.description': 'Description',
        'activityLog.header.time': 'Time',
        'activityLog.filter.searchPlaceholder': 'Search description, user, or table...',
        'activityLog.filter.allActions': 'All Actions',
        'activityLog.filter.create': 'Create',
        'activityLog.filter.update': 'Update',
        'activityLog.filter.delete': 'Delete',
        'activityLog.filter.login': 'Login',
        'activityLog.filter.logout': 'Logout',
        'activityLog.selection.selected': 'log(s) selected',
        'activityLog.selection.onPage': 'on this page',
        'activityLog.selection.from': 'from',
        'activityLog.selection.total': 'total logs (all pages)',
        'activityLog.selection.selectAll': 'Select all {total} logs',
        'activityLog.selection.loading': 'Loading...',
        'activityLog.selection.cancel': 'Cancel Selection',
        'activityLog.delete.button': 'Delete ({count}) Selected',
        'activityLog.delete.title': 'Delete Activity Logs',
        'activityLog.delete.confirm': 'Are you sure you want to delete {count} selected activity logs? This action cannot be undone.',
        'activityLog.delete.confirmAction': 'Yes, Delete',
        'activityLog.delete.cancel': 'Cancel',
        'activityLog.detail.title': 'Activity Detail',
        'activityLog.detail.noDescription': 'No detailed description.',
        'activityLog.detail.entity': 'Related Entity',
        'activityLog.detail.technical': 'Technical Information',
        'activityLog.detail.userStamp': 'User Stamp',
        'activityLog.detail.table': 'Table:',
        'activityLog.detail.recordId': 'Record ID:',
        'activityLog.detail.ipAddress': 'IP Address',
        'activityLog.detail.serverTime': 'Server Time',
        'activityLog.empty.title': 'No activity logs',
        'activityLog.empty.description': 'No activities recorded matching this filter.',
    }
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: ReactNode }) {
    const [language, setLanguageState] = useState<Language>('id')
    const [mounted, setMounted] = useState(false)

    useEffect(() => {
        // Load language preference from localStorage
        const savedLanguage = localStorage.getItem('language') as Language
        if (savedLanguage && (savedLanguage === 'id' || savedLanguage === 'en')) {
            setLanguageState(savedLanguage)
        }
        setMounted(true)
    }, [])

    const setLanguage = (lang: Language) => {
        setLanguageState(lang)
        localStorage.setItem('language', lang)
    }

    const t = (key: string, params?: Record<string, string | number>): string => {
        let translation = translations[language][key] || key

        if (params) {
            Object.entries(params).forEach(([paramKey, value]) => {
                translation = translation.replace(`{${paramKey}}`, String(value))
            })
        }

        return translation
    }

    // We always render the provider to avoid "useLanguage must be used within a LanguageProvider" errors in children.
    // Hydration is handled by ensuring the initial state is consistent.

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    )
}

export function useLanguage() {
    const context = useContext(LanguageContext)
    if (context === undefined) {
        throw new Error('useLanguage must be used within a LanguageProvider')
    }
    return context
}
