import { NextRequest, NextResponse } from 'next/server'
import { cookies } from 'next/headers'
import * as fs from 'fs'
import * as path from 'path'

export async function POST(request: NextRequest) {
    try {
        const body = await request.json()
        const { databaseName } = body

        if (!databaseName) {
            return NextResponse.json({
                success: false,
                error: 'Database name is required'
            }, { status: 400 })
        }

        // Store selected database in a cookie
        const cookieStore = await cookies()
        cookieStore.set('selected_database', databaseName, {
            httpOnly: true,
            secure: process.env.NODE_ENV === 'production',
            sameSite: 'lax',
            maxAge: 60 * 60 * 24 * 365 // 1 year
        })

        // Also update .env.local file with new DATABASE_URL
        const host = process.env.POSTGRES_HOST || 'localhost'
        const port = process.env.POSTGRES_PORT || '5432'
        const user = process.env.POSTGRES_USER || 'postgres'
        const password = process.env.POSTGRES_PASSWORD || 'postgres'

        const newDatabaseUrl = `postgresql://${user}:${password}@${host}:${port}/${databaseName}?schema=public`

        // Write to .env.local file
        const envLocalPath = path.join(process.cwd(), '.env.local')
        const envContent = `# Auto-generated by Database Manager - Selected Database\nDATABASE_URL="${newDatabaseUrl}"\n`

        fs.writeFileSync(envLocalPath, envContent, 'utf8')

        return NextResponse.json({
            success: true,
            message: 'Database selected successfully',
            database: databaseName,
            redirectUrl: '/login',
            needsRestart: false
        })

    } catch (error: any) {
        console.error('Select database error:', error)
        return NextResponse.json({
            success: false,
            error: error.message || 'Failed to select database'
        }, { status: 500 })
    }
}
